In [ ]:
# reducing fractions
# if gcd(a,b) = c, then a/b = (a/c*c)/(b/c*c) = (a/c)/(b/c)
# gdc(6/15) = 3, so 6/15 = (6/3*3)/(15/3*3) = (6/3)/(15/3) = (2/5)

In [3]:
from IPython.display import display, Math
import numpy as np
import sympy as sym
import math

In [7]:
math.gcd(4,16) # greatest common denominator

4

In [18]:
# application or gcd

a = 16
b = 88

fact = math.gcd(a,b)

display(Math('\\frac{%g}{%g} = \\frac{%g\\times %g}{%g \\times %g}' %(a,b,a/fact,fact,b/fact,fact)))

<IPython.core.display.Math object>

In [47]:
# exercise1.independant.show that gcd(ca,cb) = cgcd(a,b)
a,b,c = sym.symbols('a,b,c')
ca = 45
cb = 60
c = [10]
c[0] = math.gcd(ca,cb)


print(ca/c[0])

# display(Math('\\text{the gcd of} %g,%g = %g \\times \\text\\{the gcd of} %g\\times%g ' %(ca,cb,c[0],ca,cb)))
display(Math('%g,%g = %g \\times  %g\\times%g ' %(ca,cb,c[0],ca/c[0],cb/c[0])))

3.0


<IPython.core.display.Math object>

In [207]:
# exercise2.independent
rownums = range(0,10)
colnums = range(0,15)

mat = np.zeros((len(rownums),len(colnums)),dtype=int)+99# creates matrix called mat

# for rowi in rownums: # sets mat elements = 99
#     for coli in colnums:
#         mat[rowi,coli] = 99
print(mat)

[[99 99 99 99 99 99 99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99 99 99 99 99 99 99]]


In [237]:
# experimental
rownums = range(0,10)
colnums = range(0,15)

mat = np.zeros((len(rownums),len(colnums)),dtype=int)+99# creates matrix called mat

# for rowi in rownums:
#     for coli in colnums:
#         mat[rowi,coli] = math.gcd(rowi,coli)
print(mat)

[[99 99 99 99 99 99 99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99 99 99 99 99 99 99]]


In [203]:
# exercise1.instructed

a,b,c = sym.symbols('a,b,c')

print(sym.gcd(a*c,b*c))
print(c*sym.gcd(a,b))

a = 15
b = 6
c = 3

print(math.gcd(a*c,b*c))
print(c*math.gcd(a,b)) 

c
c
9
9


In [7]:
# exercise2.instructed
ro = 10
co = 15

gcdMat = np.zeros([ro,co],dtype=int)+99

for rowi in range(0,n):
    for coli in range(0,m):
        gcdMat[rowi,coli] = math.gcd(rowi+1,coli+1)

display(Math(sym.latex(sym.sympify(gcdMat))))



NameError: name 'n' is not defined

In [4]:
m

NameError: name 'm' is not defined