In [ ]:
# "A" = whole matrice. "a" = element in matrice. subscript = row,column. ie "A [a(sub)1,2]"

In [62]:
from IPython.display import display, Math
import sympy as sym
import numpy as num

In [43]:
from IPython.display import display, Math
import sympy as sym
import numpy as np

In [48]:
A = np.array([ [1,2],[3,4] ])

print(A)

display(Math(sym.latex(sym.sympify(A))))

[[1 2]
 [3 4]]


<IPython.core.display.Math object>

In [58]:
mat = np.zeros([4,6]) # np.zeros([rows,columns]) creates matrice with specified row,col

# mat[2,4] = 7
# mat[0,1] = 2

mat

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [59]:

numrange = range(0,4)

for rowi in numrange:
    for coli in numrange:
        mat[rowi,coli] = (-1)**(rowi+coli)
        
mat

array([[ 1., -1.,  1., -1.,  0.,  0.],
       [-1.,  1., -1.,  1.,  0.,  0.],
       [ 1., -1.,  1., -1.,  0.,  0.],
       [-1.,  1., -1.,  1.,  0.,  0.]])

In [74]:
# exercise. independant
from sympy.abc import x
from sympy.abc import y
numrange = range(0,3)
mat = np.zeros([3,3])
fxy = (4+x)*(2-y) # this is the expression for this exersise
test = (4+3)*(2-8)

for rowi in numrange:
    for coli in numrange:
        mat[rowi,coli] = fxy.subs({x:rowi,y:coli})
display(mat)
display(Math(sym.latex(sym.sympify(mat))))

array([[ 8.,  4.,  0.],
       [10.,  5.,  0.],
       [12.,  6.,  0.]])

<IPython.core.display.Math object>

In [81]:
# exersise. instructed
x,y = sym.symbols('x,y')
fxy = (4+x)*(2-y)

xyset = range(0,3)

outmat = np.zeros([len(xyset),len(xyset)])

for i in xyset:
    for j in xyset:
        outmat[i,j] = fxy.subs({x:i,y:j})
        
display(Math(sym.latex(sym.sympify(outmat))))

<IPython.core.display.Math object>

In [90]:
a = (-1)**(1+1)
# b = (-1)**(a+b)
# c = (-1)**(b+c)

a

1